trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

  variables:
    - name: deploymentDefaultLocation
      value: westus

  jobs:   
  - job: Build
  
  steps:
  - script: |
            echo Hello $(parameters.environmentType)
            npm install
            npm run build --if-present          
    displayName: 'npm build'
    
stages:

# Lint the Bicep file.
- stage: Lint
  jobs: 
  - template: /pipeline-templates/lint.yml

# Deploy to the test environment.
- template: deploy/pipeline-templates/lint.yml
  parameters:
    environmentType: Test
    resourceGroupName:  $(resourceGroupName)
    serviceConnectionName: $(testingserviceConnectionName)
    location: deploymentDefaultLocation

# Deploy to the production environment.
- template: deploy/pipeline-templates/lint.yml
  parameters:
    environmentType: Production
    resourceGroupName:  $(resourceGroupName)
    serviceConnectionName: $(prodserviceConnectionName)
    location: deploymentDefaultLocation