trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: deploymentDefaultLocation
  value: westus

jobs:
- job:
  steps:
  
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: nest-app\main.bicep
      overrideParameters: >
        -environmentType $(EnvironmentType)
        -deploybicepManualsStorageAccount $(deploybicepManualsStorageAccount)