trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: deploymentDefaultLocation
  value: westus

jobs:   
- job: Build
 
  steps:
  - script: |
            npm install
            npm run build --if-present
    displayName: 'npm install, build'
    
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: '**/main.bicep' 
      overrideParameters: >
        -environmentType $(EnvironmentType)
        -deploynestManualsStorageAccount $(deploynestManualsStorageAccount)
      

