trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: deploymentDefaultLocation
  value: westus

jobs:   
- job: Build
 
  steps:
  - script: |
            npm install
            npm run build --if-present
            npm runs start --if present
    displayName: 'npm build'
    
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'tesing-bicep-connection'
      appType: 'webAppLinux'
      appName: 'testing-nest'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      startUpCommand: 'pm2 start dist/main.js --no-daemon'
 
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: '**/main.bicep' 
      overrideParameters: >
        -environmentType $(EnvironmentType)
        -deploynestManualsStorageAccount $(deploynestManualsStorageAccount)
  
  

      

