trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

  variables:
    - name: deploymentDefaultLocation
      value: westus

  jobs:   
  - job: Build
  
  steps:
  - script: |
            echo Hello $(parameters.environmentType)
            npm install
            npm run build --if-present          
    displayName: 'npm build'
    
stages:

# Lint the Bicep file.
- stage: Lint
  jobs: 
  - template: lint.yml

# Deploy to the test environment.
- template: deploy.yml
  parameters:
    environmentType: Test
    resourceGroupName: testing
    serviceConnectionName: testing-service-connection

# Deploy to the production environment.
- template: deploy.yml
  parameters:
    environmentType: Production
    resourceGroupName: testing
    serviceConnectionName: prod-service-connection