# az-login.yaml
name: Display Account Info

on:
  push:

jobs:
  login:
    runs-on: self-hosted

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Display Azure account info
        run: az account show -o yaml
