# az-login.yaml
name: Display Account Info

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - name: "Login and do something"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.24.2
        inlineScript: |
          az login --identity
          az group list
